// Assemble web/ — the public static copy of the phone hand-off page, for
// GitHub Pages / Vercel / Cloudflare Pages. It is the same map + routing engine
// the kiosk serves, minus the server: destination comes from ?d=<slug>, the
// data is a snapshot taken at build time.
//
//   node tools/build-web.mjs
//
// Deploy web/ as a static site. A GitHub Action does this on every push
// (.github/workflows/deploy-web.yml).

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'web');
const PUB = path.join(ROOT, 'public');

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

// --- index.html: mobile.html without the kiosk-only <meta> and <base> --------
let html = fs.readFileSync(path.join(PUB, 'mobile.html'), 'utf8')
  .replace(/^\s*<meta name="kiosk-hosted"[^>]*>\s*\n/m, '')
  .replace(/^\s*<base href="\/"\s*\/?>\s*\n/m, '')
  .replace('</head>', '  <link rel="manifest" href="manifest.webmanifest" />\n</head>')
  .replace('</body>',
    "  <script>if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(function(){});</script>\n</body>");
fs.writeFileSync(path.join(OUT, 'index.html'), html);

// --- copy the assets the page loads ---------------------------------------
const JS = ['georef.js', 'geo-overlay.js', 'campus-data.js', 'walkpaths.js', 'routing.js', 'mobile.js'];
fs.mkdirSync(path.join(OUT, 'js'), { recursive: true });
for (const f of JS) fs.copyFileSync(path.join(PUB, 'js', f), path.join(OUT, 'js', f));

fs.cpSync(path.join(PUB, 'vendor', 'leaflet'), path.join(OUT, 'vendor', 'leaflet'), { recursive: true });

fs.mkdirSync(path.join(OUT, 'assets'), { recursive: true });
for (const f of ['groundFloor_layer.svg', 'secondFloor_layer.svg']) {
  fs.copyFileSync(path.join(PUB, 'assets', f), path.join(OUT, 'assets', f));
}

fs.cpSync(path.join(PUB, 'tiles'), path.join(OUT, 'tiles'), { recursive: true });

// --- service worker: shell precached, big assets cached on first use --------
const VERSION = new Date().toISOString().slice(0, 16).replace(/[-:T]/g, '');
const shell = ['', 'index.html', 'manifest.webmanifest', 'vendor/leaflet/leaflet.css', 'vendor/leaflet/leaflet.js']
  .concat(JS.map(f => 'js/' + f));
fs.writeFileSync(path.join(OUT, 'sw.js'), `// generated by tools/build-web.mjs
const V = 'slsu-kiosk-${VERSION}';
const SHELL = ${JSON.stringify(shell, null, 0)};
self.addEventListener('install', e => {
  e.waitUntil(caches.open(V).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== V).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(
    caches.match(req).then(hit => hit || fetch(req).then(res => {
      if (res.ok) { const copy = res.clone(); caches.open(V).then(c => c.put(req, copy)); }
      return res;
    }).catch(() => hit))
  );
});
`);

fs.writeFileSync(path.join(OUT, 'manifest.webmanifest'), JSON.stringify({
  name: 'SLSU Campus Walking Directions',
  short_name: 'SLSU Campus',
  display: 'standalone',
  background_color: '#aab7ad',
  theme_color: '#0F7A87',
  start_url: './'
}, null, 2));

fs.writeFileSync(path.join(OUT, '.nojekyll'), '');
fs.writeFileSync(path.join(OUT, 'CNAME.example'), '# rename to CNAME and put a custom domain here if you set one up\n');

// --- report --------------------------------------------------------------
function bytes(dir) {
  let n = 0;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    n += e.isDirectory() ? bytes(p) : fs.statSync(p).size;
  }
  return n;
}
const total = bytes(OUT);
const tiles = fs.readdirSync(path.join(OUT, 'tiles'), { recursive: true }).filter(f => f.endsWith('.png')).length;
console.log('web/ built:');
console.log('  ' + (total / 1e6).toFixed(1) + ' MB total, ' + tiles + ' tiles');
console.log('  index.html + ' + JS.length + ' scripts + leaflet + 2 floor SVGs + service worker');
console.log('\ndeploy web/ as a static site; the QR should point at  <site>/?d=<slug>&from=<x>,<y>');
